# Generated by Django 4.1.5 on 2023-02-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('from_where', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed_date', models.DateField()),
                ('website_url', models.URLField(blank=True)),
            ],
        ),
    ]
