# Generated by Django 4.1.5 on 2023-02-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(),
        ),
    ]
