# Generated by Django 4.1.5 on 2023-02-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_mainpicture_alter_project_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/myself')),
            ],
        ),
        migrations.AlterField(
            model_name='mainpicture',
            name='image',
            field=models.ImageField(upload_to='images/myself'),
        ),
    ]
