# Generated by Django 4.1.5 on 2023-02-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_aboutpicture_alter_mainpicture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gitpod_url',
            new_name='github_url',
        ),
    ]
