# Generated by Django 4.1.5 on 2023-02-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_gitpod_url_project_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/work'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
