# Generated by Django 4.1.5 on 2023-02-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
