# Generated by Django 4.1.5 on 2023-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_mycv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='meta_type',
            field=models.CharField(choices=[('app', 'App'), ('web', 'Web')], default='web', max_length=100),
        ),
    ]
