# Generated by Django 4.1.5 on 2023-02-06 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_meta_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('app development', 'App Development'), ('web development', 'Web Development')], default='web development', max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='completed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
