# Generated by Django 4.1.5 on 2023-02-06 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycv',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
